/*
 * 直接模式
 *
 * 接入jugugu区块链全包的全部接口，访问IP需要连续管理员，添加业务服务器IP
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// InlineResponse2001 struct for InlineResponse2001
type InlineResponse2001 struct {
	// 响应状态分为：-1,0,1 分别代表响应错误、响应提示、响应成功
	State string `json:"state"`
	// 响应状态为-1时该值为错误信息。响应状态为0时，该值为响应提示信息。响应状态为1时该值为空字符串
	Msg string `json:"msg"`
	Phone string `json:"phone"`
	// 验证码图片的ID值
	Virifycodeid string `json:"virifycodeid"`
	// data:image/png;base64
	Virifyimage string `json:"virifyimage"`
	// 树图区块链地址
	Confluxaddress string `json:"confluxaddress"`
	// 以太坊、Arbitrum、polygon、BSC等EVM链地址
	Ethaddress string `json:"ethaddress"`
	// 用户登录识别令牌，用于后续多个函数的交互，作为输入参数
	Token string `json:"token"`
}
